webBinh/Models/Project.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webBinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.columns = new HashSet<column>();
        }
    
        public int id_project { get; set; }
        public string mota { get; set; }
        public string title { get; set; }
        public string ownerIds { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<column> columns { get; set; }
        public virtual nguoiDung nguoiDung { get; set; }
    }
}

webBinh/Models/column.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webBinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class column
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public column()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int id_column { get; set; }
        public Nullable<int> id_project { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}

webBinh/Controllers/columnsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using webBinh.Models;

namespace webBinh.Controllers
{
    public class columnsController : Controller
    {
        private webNangCaoQLDA2Entities1 db = new webNangCaoQLDA2Entities1();

        // GET: columns
        public ActionResult Index()
        {
            var columns = db.columns.Include(c => c.Project);
            return View(columns.ToList());
        }

        // GET: columns/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            column column = db.columns.Find(id);
            if (column == null)
            {
                return HttpNotFound();
            }
            return View(column);
        }

        // GET: columns/Create
        
       
        public async Task<ActionResult> CreateColumn([Bind(Include = "id_column,title,createdAt")] column column, string idpr)
        {
          
                using (var httpClient = new HttpClient())
                {
                    var url = "http://localhost:5224/createColumn";
                    var content = new FormUrlEncodedContent(new[]
                    {
                        new KeyValuePair<string, string>("id_column", column.id_column.ToString()),
                        new KeyValuePair<string, string>("IdProject",idpr),
                        new KeyValuePair<string, string>("Title", column.title),
                        new KeyValuePair<string, string>("CreatedAt", column.createdAt.ToString())
                    });

                    var response = await httpClient.PostAsync(url, content);

                    if (response.IsSuccessStatusCode)
                    {
                        var responseData = await response.Content.ReadAsStringAsync();
                        if (responseData.Contains("ok"))
                        {
                            return RedirectToAction("index", "project");
                        }
                    }
                    else
                    {
                        ViewBag.ErrorMessage = "Không thể kết nối với API.";
                    }
                }
            return View();
            
           
        }

        // GET: columns/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            column column = db.columns.Find(id);
            if (column == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_project = new SelectList(db.Projects, "id_project", "mota", column.id_project);
            return View(column);
        }

        // POST: columns/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_column,id_project,title,createdAt")] column column)
        {
            if (ModelState.IsValid)
            {
                db.Entry(column).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_project = new SelectList(db.Projects, "id_project", "mota", column.id_project);
            return View(column);
        }

        // GET: columns/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            column column = db.columns.Find(id);
            if (column == null)
            {
                return HttpNotFound();
            }
            return View(column);
        }

        // POST: columns/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            column column = db.columns.Find(id);
            db.columns.Remove(column);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

webBinh/Controllers/projectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using Newtonsoft.Json;
using webBinh.Models;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using System.Data.Entity;
using System.Text;

namespace webBinh.Controllers
{
    public class projectController : Controller
    {
        // GET: project
        //string sdt = "0839976113";
        private webNangCaoQLDA2Entities1 db = new webNangCaoQLDA2Entities1();
        List<webBinh.Models.Task> task = new List<webBinh.Models.Task>();
        List<webBinh.Models.Project> project = new List<webBinh.Models.Project>();
     

        public ActionResult Index(string sdt)
        {
            sdt = "0839976113";
            using (var httpClient = new HttpClient())
            {
                var response = httpClient.GetAsync("http://localhost:5224/GetTenProject?sdt="+sdt).Result; // Thay URL bằng URL API của bạn

                if (response.IsSuccessStatusCode)
                {
                    var responseData = response.Content.ReadAsStringAsync().Result;

                    project = JsonConvert.DeserializeObject<List<Project>>(responseData);
                }
                else
                {
                    ViewBag.ErrorMessage = "Không thể kết nối với API.";
                }
            }
            return View(project.ToList());
        }
        
        public  ActionResult column(int id_project, string sdt)
        {
            using (var httpClient = new HttpClient())
            {
                var response = httpClient.GetAsync("http://localhost:5224/GetTenProject?sdt=" + sdt).Result; // Thay URL bằng URL API của bạn

                if (response.IsSuccessStatusCode)
                {
                    var responseData = response.Content.ReadAsStringAsync().Result;

                    project = JsonConvert.DeserializeObject<List<Project>>(responseData);
                }
                else
                {
                    ViewBag.ErrorMessage = "Không thể kết nối với API.";
                }
            }
            ViewBag.project = project.ToList();

            var ten= project.Where(i=>i.id_project==id_project).FirstOrDefault();
            ViewBag.ten = ten.title;
            ViewBag.id=id_project;


            using (var httpClient = new HttpClient())
            {
                var response = httpClient.GetAsync("http://localhost:5224/GetTask?sdt=" + sdt).Result; // Thay URL bằng URL API của bạn

                if (response.IsSuccessStatusCode)
                {
                    var responseData = response.Content.ReadAsStringAsync().Result;

                    task = JsonConvert.DeserializeObject<List<webBinh.Models.Task>>(responseData);
                }
                else
                {
                    ViewBag.ErrorMessage = "Không thể kết nối với API.";
                }
            }
            ViewBag.task=task.ToList();


            List<webBinh.Models.column> columns = new List<webBinh.Models.column>();
            using (var httpClient = new HttpClient())
            {
                var response = httpClient.GetAsync("http://localhost:5224/GetColumn?id_project=" + id_project).Result; // Thay URL bằng URL API của bạn

                if (response.IsSuccessStatusCode)
                {
                    var responseData = response.Content.ReadAsStringAsync().Result;

                    columns = JsonConvert.DeserializeObject<List<webBinh.Models.column>>(responseData);
                }

            }
            return View(columns.ToList());
        }

        public async Task<ActionResult> createProject([Bind(Include = "id_project,mota,title,ownerIds,createdAt")] Project project)
        {
            using (var httpClient = new HttpClient())
            {
                var url = "http://localhost:5224/createPro";
                var content = new FormUrlEncodedContent(new[]
                {
            new KeyValuePair<string, string>("id_project", project.id_project.ToString()),
            new KeyValuePair<string, string>("Mota", project.mota),
            new KeyValuePair<string, string>("Title", project.title),
            new KeyValuePair<string, string>("OwnerIds", project.ownerIds),
            new KeyValuePair<string, string>("CreatedAt", project.createdAt.ToString())
        });

                var response = await httpClient.PostAsync(url, content);

                if (response.IsSuccessStatusCode)
                {
                    var responseData = await response.Content.ReadAsStringAsync();
                    if (responseData.Contains("ok"))
                    {
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    ViewBag.ErrorMessage = "Không thể kết nối với API.";
                }
            }
            return View(project);
        }

        //get prj to update
        public async Task<ActionResult> EditProject(int id)
        {
            var project = await db.Projects.FindAsync(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: project/editProject
        [HttpPost]
        public async Task<ActionResult> EditProject(Project project)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    using (var httpClient = new HttpClient())
                    {
                      

                        var url = $"http://localhost:5224/updatePro?id_project={project.id_project}&Mota={project.mota}&Title={project.title}";
                        var emptyContent = new StringContent("", System.Text.Encoding.UTF8, "application/json");

                        var response = await httpClient.PutAsync(url, emptyContent);
                        if (response.IsSuccessStatusCode)
                        {
                            return RedirectToAction("index");
                        }
                        else
                        {
                            ModelState.AddModelError("", "Không thể cập nhật dự án.");
                        }
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", $"Lỗi khi cập nhật: {ex.Message}");
                }
            }
            return View(project);
        }


        //del prj with id
        [HttpPost]
        public async Task<ActionResult> DeleteProject(int id_project)
        {
            try
            {
                // Gửi yêu cầu DELETE đến API
                using (var httpClient = new HttpClient())
                {
                    var apiUrl = $"http://localhost:5224/deleteProject/{id_project}";
                    var response = await httpClient.DeleteAsync(apiUrl);

                    if (response.IsSuccessStatusCode)
                    {
                        // Lưu thông báo thành công
                        TempData["SuccessMessage"] = "Xóa project thành công.";
                    }
                    else
                    {
                        // Lưu thông báo lỗi
                        var errorContent = await response.Content.ReadAsStringAsync();
                        TempData["ErrorMessage"] = $"Không thể xóa project: {errorContent}";
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Lỗi khi xóa: {ex.Message}";
            }

            // Quay lại trang Index sau khi xử lý
            return RedirectToAction("Index");
        }


    }
}

webBinh/Views/project/column.cshtml
@model IEnumerable<webBinh.Models.column>

       
@{
    ViewBag.Title = "column";
}
<style>
    .title_box {
        text-align: center;
        font-size:25px;
       margin:30px;
       font-weight:bold;
    }

    .menu {
        border: solid 1px;
        justify-content: center;
        box-sizing: border-box;
        width: 25%;
        float: left;
    }

    .menu ul {
        list-style-type: none;
        padding: 0;
        box-sizing: border-box;
    }

    .menu li {
        width: 95%;
        height: 40px;
        margin: 10px;
        padding: 0 10px;
        background-color: aquamarine;
        border: solid 1px;
        line-height: 40px;
        white-space: nowrap; /* Không cho phép xuống dòng */
        overflow: hidden; /* Ẩn phần văn bản tràn ra ngoài */
        text-overflow: ellipsis;
        border-radius: 20px;
    }
    .menu li a {
        color: blue; /* Màu chữ đỏ cho liên kết */
        text-decoration: none; /* Loại bỏ gạch dưới */
    }
    .content{
        width:75%;
        float:left;

    }
    .column{
        width:30%;
        padding: 10px;
        border:solid 1px;
        height:500px;
        margin:2px;
        float:left;
        border-radius:30px;
  
    }
     .column a {
        color: blue; /* Màu chữ đỏ cho liên kết */
        text-decoration: none; /* Loại bỏ gạch dưới */
        
    }
    .item-column {
        width: 100%;
        background-color: greenyellow;
        border-radius: 20px;
        border: 1px solid;
        margin: 10px 0;
        font-size: 20px;
        padding:5px;
    }
    .add{
        width:50px;
        height:30px;
        border-radius:5px;
        background-color:blue;
        text-align:center;
        color:white;
        margin:0 auto;
    }
 </style>
<div class="menu">
    <div class="title_box">Project của tôi</div>
    <ul class="left_menu">

        @foreach (var item in ViewBag.project)
        {
            <li>
                <a href="column?id_project= @item.id_project&sdt=0839976113"> @item.title </a>
            </li>
        }

    </ul>
    @{
        webBinh.Models.Project x = null;
    }
    <div class="add">
        @Html.ActionLink("+", "createProject", new { project = x })
    </div>
</div>

<div class="content">
    <div class="title_box">Các phần của  @ViewBag.ten</div>

    @foreach (var item in Model)
    {
        <div class="column">

            @item.title
            <br />
            <hr />

            @foreach (var i in ViewBag.task)
            {
                if (@i.id_column == item.id_column)
                {
                    <div class="item-column">
                        <a href="#"> @i.title  </a>
                    </div>

                }
            }
            <div class="add">
                +
            </div>
        </div>

    }
    @{
        webBinh.Models.column k = null;
        
    }
    <div class="column">
        <a href="@Url.Action("CreateColumn", "columns", new {column =k, idpr = ViewBag.id})">Add</a>

    </div>


</div>

webBinh/Views/project/createProject.cshtml
@model webBinh.Models.Project
@using System;
@using System.Collections.Generic;
@using System.Linq;
@{
    ViewBag.Title = "createProject";
}

<style>
    .form{
        width:500px;
        border:2px solid;
        padding:20px 50px;
        margin:0 auto;
    }
    .form>h2{
        text-align:center;
    }
    .nhap{
        
       
    }
    .submit{
        border: 2px solid;
        border-radius: 10px;
        background-color:chartreuse;
        text-align:center;
        width:150px;
        float:right;
        display:inline;
    }
    .submit:hover {
        background-color: coral;
        box-shadow: 0px 0px 10px 5px  red  ;
    }

 
 </style>
@using (Html.BeginForm("createProject", "project", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form">
    <h2>Thêm dự án mới</h2>
    <hr />
    @{
        string ownerid = "0839976113";
        DateTime ngaytao = DateTime.Now;
        int idpr = 0;


        using (var context = new webBinh.Models.webNangCaoQLDA2Entities1())
        {
            int maxId = context.Projects.Max(i => i.id_project);
            idpr = maxId + 1;
        }

    }

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.Hidden("id_project", idpr.ToString())
    @Html.Hidden("ownerIds", ownerid)
    @Html.Hidden("createdAt", ngaytao)

    <div class="nhap">
        <h4>Tiêu đề dự án</h4>
        @Html.TextAreaFor(model => model.title, new { @class = "inputText", rows = 3, cols = 80 })
        @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })

    </div>
    <div class="nhap">
        <h4> Mô tả cho dự án:</h4>

        @Html.TextAreaFor(model => model.mota, new { @class = "inputText", rows = 5, cols = 80 })
        @Html.ValidationMessageFor(model => model.mota, "", new { @class = "text-danger" })

    </div>


    <div class="submit">
        <input type="submit" value="Thêm" class="btn btn-default" />
    </div>
    <div class="back">
        @Html.ActionLink("Quay lại trang chủ", "index")
    </div>
</div>
}

webBinh/Views/project/editProject.cshtml
@model webBinh.Models.Project
@using System;
@using System.Collections.Generic;
@using System.Linq;
@{
    ViewBag.Title = "editProject";
}

<style>
    .form{
        width:500px;
        border:2px solid;
        padding:20px 50px;
        margin:0 auto;
    }
    .form>h2{
        text-align:center;
    }
    .nhap{
        
       
    }
    .submit{
        border: 2px solid;
        border-radius: 10px;
        background-color:chartreuse;
        text-align:center;
        width:150px;
        float:right;
        display:inline;
    }
    .submit:hover {
        background-color: coral;
        box-shadow: 0px 0px 10px 5px  red  ;
    }

 
 </style>
@*@using (Html.BeginForm("editProject", "project", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form">
    <h2>Sửa thông tin dự án</h2>
    <hr />

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.id_project) // Giữ lại id của dự án
    @Html.HiddenFor(model => model.ownerIds)   // Giữ lại ownerId
    @Html.HiddenFor(model => model.createdAt)   // Giữ lại createdAt0*@

<div class="nhap">
    <h4>Tiêu đề dự án</h4>
  

    <form action="@Url.Action("editProject", "project")" method="post">
     
        

        <div class="form-group" style="display: none;">
            @Html.LabelFor(model => model.id_project, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_project, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_project, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mota, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mota, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mota, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="display: none;">
            @Html.LabelFor(model => model.ownerIds, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ownerIds, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ownerIds, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="display: none;">
            @Html.LabelFor(model => model.createdAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.createdAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.createdAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="button-container">
            <button type="submit">Lưu thay đổi</button>
        </div>
    </form>


    <div>
        <div>
            <form method="post" action="@Url.Action("DeleteProject", "Project")">
                <input type="hidden" name="id_project" value="@Model.id_project" />
                <button type="submit" class="cancel">Xóa</button>
            </form>
        </div>

    </div>

</div>

webBinh/Views/project/index.cshtml
@model IEnumerable<webBinh.Models.Project>
@{
    ViewBag.Title = "index";
}
<style>
    .title_box{
        text-align:center;
    }
    .menu {
        border: solid 1px;
        justify-content: center;
        box-sizing: border-box;
        width: 25%;
        float: left;
    }
    .menu ul {
        list-style-type: none;
        padding:0;
        box-sizing:border-box;
    }
    .menu li {
        width: 95%;
        height: 40px;
        margin: 10px;
        padding: 0 10px;
        background-color: aquamarine;
        border: solid 1px;
        line-height: 40px;
        white-space: nowrap; /* Không cho phép xuống dòng */
        overflow: hidden; /* Ẩn phần văn bản tràn ra ngoài */
        text-overflow: ellipsis;
        border-radius:20px;
        
    }
    .menu li a {
        color: blue; /* Màu chữ đỏ cho liên kết */
        text-decoration: none; /* Loại bỏ gạch dưới */
    }

    .add {
        width: 50px;
        height: 30px;
        border-radius: 5px;
        background-color: blue;
        text-align: center;
        color: white;
        margin: 0 auto;
    }
</style>
<div class="menu">
    <div class="title_box">Project của tôi</div>
    <ul class="left_menu">
        @foreach (var item in Model)
        {
            <li style="display: flex; justify-content: space-between; align-items: center;">
                <span>@Html.ActionLink(item.title, "column", new { id_project = item.id_project, sdt = "0839976113" })</span>
                <span>
                    @Html.ActionLink("Sửa", "editProject", new { id = item.id_project }, new { style = "color: blue; text-decoration: none;" })
                </span>
            </li>
        }
    </ul>
    @{ 
        webBinh.Models.Project x = null;
    }
    <div class="add">
        @Html.ActionLink("+", "createProject", new { project =x })
    </div>

</div>